Repository justincase-jp/blea, pull requests merged in 2022-02, with the labels that each got.

#20 feat: event test
  src/integ.default.ts
  src/org-events.ts
  test/org-events.test.ts
Labels: size/L

#23 chore: deps update monday
  .projenrc.js
Labels: size/XS

#19 feat(org-account-init|org-stackset): デプロイできるところまで
  .editorconfig
  .eslintrc.json
  .gitattributes
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  API.md
  README.md
  lambda/health/consts.ts
  lambda/health/handler.ts
  lambda/health/healthClass.ts
  lambda/health/slack-webhook-api.ts
  package.json
  src/index.ts
  src/integ.audit.default.ts
  src/integ.default.ts
  src/integ.root.default.ts
  src/lambda/disable-securityhub-function.ts
  src/lambda/disable-securityhub.lambda.ts
  src/lambda/sw-role-function.ts
  src/lambda/sw-role.lambda.ts
  src/org-account-init.ts
  src/org-health.ts
  src/org-slack.ts
  src/org-stackset.ts
  src/type.d.ts
  yarn.lock
Labels: size/XXL

#25 fix: add_accountinitのlambda修正
  src/lambda/disable-securityhub.lambda.ts
Labels: size/XS
